---
- hosts: '{{ target_host | default("newserver") }}'

  tasks:
    - name: Install needed packages
      become: true
      package:
        name: "{{ package_needed }}"
        state: present
        update_cache: yes
    - name: Set hostname to {{ new_hostname }}
      become: yes
      hostname:
        name: '{{ new_hostname }}'
    - name: Create directory {{ path_dest_config }}
      file:
        path: '{{ path_dest_config }}'
        state: directory
        mode: '0755'
    - name: Push config to server
      synchronize:
        src: '{{ path_mount_config }}/{{ new_hostname }}/'
        dest: '{{ path_dest_config }}'
        recursive: yes
        private_key: '{{ ansible_ssh_private_key_file }}'
      delegate_to: localhost
    - name: Change config directory ownership to {{ new_username }}
      file:
        path: '{{ path_dest_config }}'
        owner: '{{ new_uid }}'
        group: '{{ new_gid }}'
        state: directory
        recurse: yes