---
- hosts: '{{ target_host | default("newserver") }}'

  tasks:
    - name: Install needed packages
      become: true
      package:
        name: "{{ package_needed }}"
        state: present
        update_cache: yes
    - name: Set hostname to {{ new_hostname }}
      become: yes
      hostname:
        name: '{{ new_hostname }}'
    - name: Push config to server
      synchronize:
        src: '{{ path_mount_config }}/{{ new_hostname }}/'
        dest: '{{ path_dest_config }}'
        recursive: yes
      delegate_to: localhost