---
- name: Find all directories with compose.yml
  find:
    paths: '{{ path_docker_stacks }}'
    patterns: "compose.yml"
    file_type: file
  register: found_compose_files

- name: Upgrade and launch all Docker stacks
  community.docker.docker_compose_v2:
    project_src: '{{ item.path | dirname }}'
    pull: always
    remove_orphans: true
  loop: "{{ found_compose_files.files }}"