---
- name: Find all directories with compose.yml
  find:
    paths: '{{ path_docker_stacks }}'
    patterns: "compose.yml"
    file_type: file
    recurse: true
  register: found_compose_files

- name: Run all Docker stacks - {{ state | default('present') }}
  community.docker.docker_compose_v2:
    project_src: '{{ item.path | dirname }}'
    pull: always
    remove_orphans: true
    state: "{{ state | default('present') }}"
  loop: "{{ found_compose_files.files }}"